[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
; Replace the placeholder value in `SMARTFLOW_CRYPTO_MASTER_KEY_HEX`
; before flashing production devices.
lib_deps =
    tzapu/WiFiManager@^2.0.17
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.5
    https://github.com/enjoyneering/AHTxx.git

[env:esp32dev-mock]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DSMARTFLOW_USE_MOCK_SENSORS=1
lib_deps =
    tzapu/WiFiManager@^2.0.17
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.5
    https://github.com/enjoyneering/AHTxx.git

[env:esp32dev-dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DSMARTFLOW_MQTT_TOPIC_PREFIX=\"group3/dev\"
lib_deps =
    tzapu/WiFiManager@^2.0.17
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.5
    https://github.com/enjoyneering/AHTxx.git

[env:esp32dev-dev-mock]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DSMARTFLOW_USE_MOCK_SENSORS=1
    -DSMARTFLOW_MQTT_TOPIC_PREFIX=\"group3/dev\"
lib_deps =
    tzapu/WiFiManager@^2.0.17
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.5
    https://github.com/enjoyneering/AHTxx.git
